// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Operation struct {
	ID          int64          `db:"id"`
	Name        sql.NullString `db:"name"`
	CreatedBy   sql.NullString `db:"created_by"`
	CreatedAt   time.Time      `db:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at"`
	UpdatedBy   sql.NullString `db:"updated_by"`
	Description sql.NullString `db:"description"`
}

type Permission struct {
	ID          int32          `db:"id"`
	Name        sql.NullString `db:"name"`
	CreatedBy   sql.NullString `db:"created_by"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	UpdatedBy   sql.NullString `db:"updated_by"`
	Description sql.NullString `db:"description"`
	IsActive    sql.NullInt16  `db:"is_active"`
	OperationID sql.NullInt32  `db:"operation_id"`
	ResourceID  sql.NullInt32  `db:"resource_id"`
}

type Policy struct {
	ID            int64          `db:"id"`
	Name          sql.NullString `db:"name"`
	CreatedBy     sql.NullString `db:"created_by"`
	CreatedAt     time.Time      `db:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at"`
	UpdatedBy     sql.NullString `db:"updated_by"`
	Description   sql.NullString `db:"description"`
	IsActive      sql.NullInt16  `db:"is_active"`
	Functionality sql.NullString `db:"functionality"`
	IsPublic      sql.NullInt16  `db:"is_public"`
}

type PolicyPermission struct {
	ID           int32          `db:"id"`
	PermissionID sql.NullInt32  `db:"permission_id"`
	PoliciyID    sql.NullInt32  `db:"policiy_id"`
	CreatedAt    sql.NullTime   `db:"created_at"`
	CreatedBy    sql.NullString `db:"created_by"`
	UpdatedAt    sql.NullTime   `db:"updated_at"`
	UpdatedBy    sql.NullString `db:"updated_by"`
	IsActive     sql.NullInt16  `db:"is_active"`
}

type Resource struct {
	ID        int64          `db:"id"`
	Name      sql.NullString `db:"name"`
	CreatedBy sql.NullString `db:"created_by"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
	UpdatedBy sql.NullString `db:"updated_by"`
}

type RolePolicy struct {
	ID        int32          `db:"id"`
	PoliciyID sql.NullInt32  `db:"policiy_id"`
	RoleID    sql.NullInt32  `db:"role_id"`
	CreatedAt sql.NullTime   `db:"created_at"`
	CreatedBy sql.NullString `db:"created_by"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	UpdatedBy sql.NullString `db:"updated_by"`
	IsActive  sql.NullInt16  `db:"is_active"`
}

type Roles struct {
	ID        int64          `db:"id"`
	RoleName  sql.NullString `db:"role_name"`
	CreatedAt time.Time      `db:"created_at"`
	CreatedBy sql.NullString `db:"created_by"`
	UpdatedBy sql.NullString `db:"updated_by"`
	UpdatedAt time.Time      `db:"updated_at"`
}
